### ISSUE TITLE
Add testing framework

### ISSUE THREAD

**Issue by pwalsh** [okfn/open-budget-survey#58]
# Description

Tests are great! Front end developers have no excuse not to do them :).

# Tasks

- [x] Get a basic setup with [mocha](https://github.com/mochajs/mocha) and [jsdom](https://github.com/tmpvar/jsdom) (we have used [zombie](https://github.com/assaf/zombie), a jsdom wrapper/superset, in place of jsdom in the past, but it looks like it is not up-to-date with latest node, and jsdom actually exposes everything we need via a simple API anyway)
- [x] Add a `tests` directory and a test runner to `package.json`
- [x] Add some really simple tests: one test for each route, to check the route exists. that is it.

Here is a relevant blog post: http://robballou.com/2014/using-jsdom-and-mocha-for-testing/

Here is some related code from our other projects:

- https://github.com/frictionlessdata/data-quality-dashboard/blob/master/tests/index.js
- https://github.com/frictionlessdata/data-quality-dashboard/blob/master/package.json#L8
- https://github.com/frictionlessdata/jsontableschema-js/tree/master/test
- https://github.com/openspending/os-admin/tree/master/tests
- https://github.com/openspending/os-viewer/tree/master/tests
- https://github.com/openspending/os-packager/tree/master/tests

**Comment by pwalsh** [comment]
done
