### ISSUE TITLE
Refactor all data access to use Indaba

### ISSUE THREAD

**Issue by pwalsh** [okfn/open-budget-survey#62]
# Description

With #61 in place, we now have the fun task of completely replacing all data access in the application with calls to the Indaba API. This requires you to make a review and assess all the ways data is called and used in the application, and then ensure that this maps to what we get from Indaba. If/where it does not, we need to raise issues early, so do a comprehensive review before starting to code.

# Tasks

- [x] Make a review of all data access in the application, write it here, including an overview of what is covered by Indaba, and any potential issues
  - [x] Overview of the ["Explorer"](https://github.com/okfn/open-budget-survey)
  - [x] Overview of the ["Tracker"](https://github.com/okfn/open-budget-survey-tracker)
- [x] Port the data access to use the Indaba API
- [x] Write some tests

**Comment by pwalsh** [comment]
@dumyan ( cc @jobarratt )

I've now noticed that the data access that this Indaba API replaces may mostly be in the Tracker app.  So, I added two sub-points above - to review API/data access across both the Explorer and the Tracker apps, then we can be absolutely sure, and @dumyan you'll best know how to proceed from there.

**Comment by pwalsh** [comment]
@dumyan can you check off above? i think this is all done, no?

**Comment by pwalsh** [comment]
done.
