### ISSUE TITLE
Integrate the Tracker directly into the Explorer

### ISSUE THREAD

**Issue by pwalsh** [okfn/open-budget-survey#63]
# Description

While the Tracker is currently a distinct codebase, the intention is to merge it and the Explorer into a single codebase. This is the first step towards this, by keeping the distinct codebases, but using an iframe to embed the important content from the Tracker into the explorer directly.

## Basic mock

The desired outcome is addressed in this basic mock.

<img width="1280" alt="option2" src="https://cloud.githubusercontent.com/assets/791678/17579655/673c7dba-5fa0-11e6-9eed-1d709fa05c1f.png">

# Tasks

- [x] Expose a new route on the [Tracker](https://github.com/okfn/open-budget-survey-tracker) that returns the content section for embedding, with no header and no footer
- [x] Expose a new env var for the explorer to point to a tracker instance/URL - this will help you test locally and then change this URL for deployments
- [x] The page that current shows under "Document Availability", **move** it to a new route/menu item called "Historical Results" (I know there is no room for it - see if you have a solution)
- [x] The page called "Document Availability" will load the Tracker, as per the Basic mock, in an iframe. the user should be able to interact within this frame as normal - clicking links and so on loads the next page in that iframe.
  - [x] I understand the widths are different - adjust what you need in this embeddable route so that the content fits well in the new iframe
  - [x] once the user starts navigating in the iframe, they lose the ability to get back to where they just where. you can add a little js widget in the embed that remembers where the user was, and lets them go back - any **simple** solution you present will be good at this stage.

**Comment by pwalsh** [comment]
done.
