### ISSUE TITLE
Updates to the calculator

### ISSUE THREAD

**Issue by pwalsh** [okfn/open-budget-survey#64]
# Description

More enhancements based on feedback with users.

# Tasks

- [x] On the buttons, write "Print/PDF" instead of print, so users know they can save to PDF using the print function
- [x] Take out the 3 lines of text after the header, and before "country datasheet"
- [x] For "Print Plain":
  - [x] Rename to "Print Survey"
  - [x] Remove "COUNTRY DATASHEET: FIJI (FJ)" (or whatever) and replace with "Survey Questions and Answers"
  - [x] Remove the two blocks under "COUNTRY DATASHEET: FIJI (FJ)" that show "2015" and "2017"
- [x] For "Print Answers":
  - [x] Rename to "Print Results"
  - [x] Change "COUNTRY DATASHEET: FIJI (FJ)" (or whatever) to:
    - [x] "COUNTRY DATASHEET: FIJI (FJ): ACTUAL RESULTS" if the results are not modified
    - [x] "COUNTRY DATASHEET: FIJI (FJ): MODIFIED {YEAR} RESULTS" if the results are modified
  - [x] *As well as* of listing the answers, with an underline for each answer for the latest year, show, underneath those answers, the result for the previous year in this format: "Answer was {LETTER} in {YEAR}"
  - [x] To make it clear that the answers are for "current year" (2017 in our case), change the heading over all answers from "Answers" to {YEAR} Answers

**Comment by dumyan** [comment]
Question about the following enhancement:

> As well as of listing the answers, with an underline for each answer for the latest year, show, underneath those answers, the result for the previous year in this format: "Answer was {LETTER} in {YEAR}"

When the calculator is initialized the default answers are those of 2015 (except when changes are saved in the URL params). So when the answer is not changed, it doesn't make much sense to describe that the answer was the same in 2015. Should the description be about the last survey before 2015?

**Comment by pwalsh** [comment]
Whatever makes sense for you is fine.
